### ISSUE TITLE
Description of neighbors.tsv

### ISSUE THREAD

**Issue by yyoshiaki** [bicycle1885/CellFishing.jl#5]
Hi, 
Could you please add a brief description of neighbors.tsv?
Best, 
Yoshiaki

**Comment by bicycle1885** [comment]
Hi, I'm very sorry for the late response.

The first line is a header like `cell,n1,n2,n3,n4,...` (here I used commans instead of tabs for readablity).
The search results start from the second line. The query cell names come in the first column, and the cells names of the nearest neighbors found in the database follows after that. The second column contains the most similar cells to the query cells in the same lines. The third column contains the second similar cells, and the fourth column contains the third similar cells, and so on.

Please feel free to email me if you have any questions about the software.
